BASE_URL = "https://www.saucedemo.com/"
BASE_ROOT = "https://www.saucedemo.com"
INVENTORY_ENDPOINT = "/inventory.html"
CARD_BADGE_ENDPOINT = "/cart.html"
CHECKOUT_ENDPOINT = "/checkout-step-one.html"
OVERVIEW_ENDPOINT = "/checkout-step-two.html"
COMPLETE_ENDPOINT = "/checkout-complete.html"
DETAILED_ITEM_ENDPOINT = "/inventory-item.html?id=4"
