SAUCE_LABS_BACKPACK_TEXT = "Sauce Labs Backpack"
SHIPPING_INFO_TEXT = "Free Pony Express Delivery!"
TAX_AMOUNT = "2.40"
TITLE_TEXT = "Checkout: Complete!"
HEADER_TEXT = "Thank you for your order!"
COMPLETE_TEXT = "Your order has been dispatched, and will arrive just as fast as the pony can get there!"